### ISSUE TITLE
Documentation Lacking around Routing Key Implications

### ISSUE THREAD

**Issue by richbria** [rabbitmq/rabbitmq-consistent-hash-exchange#13]
In my opinion you are missing some relevant information about the significance of the routing key.  The questions I would like to see answered are:

Given a single consumer what should my routing key be?  Based on the current documentation I think it should be less than thousands but as close to thousands as possible.  So is 1000 a good number?

Given the addition of a new consumer should I adjust my bindings to reflect the additional consumer ie with 1 consumer we have a routing key of 1000 but with 2 we have a routing key of 500 on each queue because we expect the same throughput but spread across multiple queues.

Also, given the previous statement is true, why is this not just a percentage of total work load?  Ie we you specify with the routing key what percentage of messages go to each queue.  (this is why I don't think the previous statement is true)

Also, I will just throw it out there that I think you should handle a # being passed as the routing key.  I started out without fully understanding and just assumed that a # would give me everything.  That caused some real headaches.

Finally, I don't want to sound like a negative nancy so I will commend you on this excellent plugin.  I will probably be sending a pull request in the near future.  Our routing keys are of this nature ID.Hash.MessageType which will cause some slight issues when the message type is different.  There is a chance that a messagem of type Foo will not go to the same queue as a message of type Bar, even though they have the same Identifier.  Therefore, the feature I will (hopefully) add is the ability to specify what segment of the routing key to hash with some pattern matching.  In our scenario something like #.#.* where hashes are matches and  *'s are ignores or something similar.

**Comment by richbria** [comment]
Any information on this would be helpful.

**Comment by arnauorriols** [comment]
My 2 cents of feedback, related to the (multiple) requests of @richbria.

In regards to improving the documentation of the routing keys usage, I would suggest adding some link to a consistent-hashing-for-dummies blog post, there are some of them quite comprehensive ([example](http://www.martinbroadhurst.com/Consistent-Hash-Ring.html) or [example](http://michaelnielsen.org/blog/consistent-hashing/)). Also, referring to the concept of points as replicas instead/as well, might help understand the usage of the routing keys quicker. 

+1 that it would be nice to have a recommendation on the magnitude of points/replicas to use based on the performance implications of the current implementation.

+1 that if would be nice being able to shard based on a segment of the routing key.

**Comment by michaelklishin** [comment]
@arnauorriols I will add your blog post links but consider starting a rabbitmq-users discussion instead of posting +1s here. The problem with +1s is that they rarely lack the important technical details that engineers need, e.g. how do you define "shard" and "segment of the routing key". Thank you.

**Comment by michaelklishin** [comment]
With a single consumer it doesn't matter because the entire hashing ring is allocated to a single "node" (queue in this case). Consistent hashing is based on a range of integer values, not percentage of the ring, historically, and changing that in this plugin would be a breaking change that affects every existing user.

Some understanding of what consistent hashing is is necessary when using this plugin. For those looking to partition a stream of messages across N consumers in a roughly even manner while also trading off total ordering, [rabbitmq-sharding](https://github.com/rabbitmq/rabbitmq-sharding) would probably be an easier to understand option.
