### ISSUE TITLE
Use retries when waiting for Mnesia tables to load

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-consistent-hash-exchange#31]
This plugin currently uses `mnesia:wait_for_tables/1`. RabbitMQ itself has moved to use a system with periodic retries instead of a single fixed value (as of `3.6.7` IIRC).

This plugin should do the same, otherwise deployments that use it will be plagued by the same cluster restart unpredictability
we've seen with a single attempt and a single timeout in the core.

**Comment by hairyhum** [comment]
@michaelklishin can you reproduce that? The plugins boot step requires the `database` boot step, which will wait with retries, so the boot step should be already clustered when it's run.

**Comment by michaelklishin** [comment]
@hairyhum I've noticed it when reading the code investigating something else. It's a good point and perhaps we can leave things as they are.
