### ISSUE TITLE
Is header hashing supported?

### ISSUE THREAD

**Issue by javiervegas** [rabbitmq/rabbitmq-consistent-hash-exchange#4]
I am pretty sure I read about header hashing in the readme, but now I can not find the reference. It seems to work with consisten hashing, but not with modulus hash.

Steps to reproduce:

1) Create a modulus-hash exchange with a hash-header header
![screen shot 2015-01-29 at 11 15 23 am](https://cloud.githubusercontent.com/assets/63576/5964409/aa485554-a7a8-11e4-8a5e-7301e2e860ce.png)
2) Apply sharding policy
<pre>
rabbitmqctl set_policy images-shard "^shard.images$" '{"shards-per-node": 2, "routing-key": "1234"}'
</pre>
3) verify queues and bindings are created
![screen shot 2015-01-29 at 11 16 19 am](https://cloud.githubusercontent.com/assets/63576/5964449/ff9fbb46-a7a8-11e4-9c93-12ec5ad491dc.png)
4) publish a message to exchange using the specified hash-header
![screen shot 2015-01-29 at 11 16 28 am](https://cloud.githubusercontent.com/assets/63576/5964461/21edf4b0-a7a9-11e4-9d10-0ea9d75591a1.png)
5) repeat previous step 10 times, increasing the value of hash-me by one each time

Expected result: One queue has 6 messages, other queue has 5

Observed result: One queue has 11 messages, the other is empty
![screen shot 2015-01-29 at 11 17 38 am](https://cloud.githubusercontent.com/assets/63576/5964496/65657e20-a7a9-11e4-9fa4-6319b74b676f.png)

**Comment by michaelklishin** [comment]
This repository is currently a mirror. Please post questions to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

**Comment by michaelklishin** [comment]
According to the 1st screenshot, you are using the modulus hash exchange from the sharding plugin. This is a different exchange type. Either use this exchange or follow the README of the sharding plugin.

**Comment by javiervegas** [comment]
Sorry, I meant to post this in rabbitmq-sharding, I apologize for the error.
