### ISSUE TITLE
Provide examples in more programming languages

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-consistent-hash-exchange#5]
We currently only have an Erlang client example.

**Comment by darkgray** [comment]
I was looking for spring-amqp support for this exchange. It seems the best way to go about it is to use a custom exchange to publish and standard way of consuming from multiple queues. I would be interested in samples as well, specially for consumption (if there is a different way).

**Comment by michaelklishin** [comment]
Done (for 3 more languages) as part of #38.
