### ISSUE TITLE
Negative routing key should result in a channel error

### ISSUE THREAD

**Issue by EddieJamsession** [rabbitmq/rabbitmq-consistent-hash-exchange#6]
Had a lot of troubles, because we set routing key to "-1", plugine just got crazy.

**Comment by michaelklishin** [comment]
Can you be more specific than "got crazy"?

**Comment by EddieJamsession** [comment]
The thread with consistent-hash was consuming alot of memory 1000x of normal usage of entire broker.

**Comment by hairyhum** [comment]
Close due to #11
