### ISSUE TITLE
Hash on AMQP Message Properties

### ISSUE THREAD

**Issue by gmr** [rabbitmq/rabbitmq-consistent-hash-exchange#7]
I'd like to add support for hash distribution on message properties such as ``message_id`` or ``correlation_id``. 

Before I write the code, I'd like validation that my proposed enhancement is what the team would like to see/merge. I'd be adding a new config value ``hash-property`` which you would specify the AMQP property that should be hashed on:

``{<<"hash-property">>, longstr, <<"message_id">>}``

To achieve this I would:

- Implement ``validate/1`` to check that if ``hash-property`` is set, the value is a valid AMQP property name. Additionally it would check to ensure that ``hash-header`` and ``hash-property`` are not both sent, failing if they are.
- Modify ``route/2`` to support ``hash-property``
- Add a new ``hash/2`` to support ``hash-property``

Does this make sense?

**Comment by videlalvaro** [comment]
Which one would have priority, hash-header or hash-property?

**Comment by gmr** [comment]
I would make it fail validation if both were set.

**Comment by videlalvaro** [comment]
I think it makes sense to hash on `message_id` or `correlation_id`, let's see what the others have to say

**Comment by gmr** [comment]
Closing this as I've now submitted #8 and we can continue the discussion there if needed.
